# Generated by Django 4.2.7 on 2023-11-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_Employe_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'ADMIN'), ('2', 'TEAMLEAD'), ('3', 'DEVELOPER')], default=1, max_length=10),
        ),
    ]
