# Generated by Django 4.2.5 on 2023-11-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_Employe_app', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='assigned_tl',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
