# Generated by Django 4.2.5 on 2023-11-09 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IT_Employe_app', '0003_remove_project_assigned_tl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='department',
        ),
    ]
