# Generated by Django 4.2.7 on 2023-11-25 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IT_Employe_app', '0006_customuser_team_lead_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='team_lead_profile',
        ),
    ]
